CREATE TABLE IF NOT EXISTS `fr24` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT,
`frid` TEXT  ,
`ymd` date ,
`addr` TEXT ,
`fcontact` int ,
`lcontact` int ,
`hex` TEXT  ,
`reg` TEXT  ,
`ac` TEXT   ,
`cs` TEXT   ,
`iso` TEXT   ,
`flon` double(8,5),
`flat` double(8,5),
`llon` double(8,5),
`llat` double(8,5),
`falt` int ,
`lalt` int ,
`fhdg` int ,
`lhdg` int ,
`fspeed` int ,
`lspeed` int ,
`fvert` int ,
`lvert` int ,
`fsq` int ,
`lsq` int ,
`gnd` tinyint ,
`flt` TEXT   ,
`al` TEXT   ,
`dep` TEXT  ,
`arr` TEXT  ,
`frdr` TEXT ,
`lrdr` TEXT ,
`fnear` TEXT,
`lnear` TEXT

);

