ICAO_Ranges = [
#   Mostly generated from the assignment table in the appendix to Chapter 9 of
#   Annex 10 Vol III, Second Edition, July 2007 (with amendments through 88-A, 14/11/2013)

  { 'start': 0x004000, 'end': 0x0043ff, 'country': "Zimbabwe", 'iso': "ZW", 'flag': "🇿🇼", 'flag_image': "Zimbabwe.png" },
  { 'start': 0x006000, 'end': 0x006fff, 'country': "Mozambique", 'iso': "MZ", 'flag': "🇲🇿", 'flag_image': "Mozambique.png" },
  { 'start': 0x008000, 'end': 0x00ffff, 'country': "South Africa", 'iso': "ZA", 'flag': "🇿🇦", 'flag_image': "South_Africa.png" },
  { 'start': 0x010000, 'end': 0x017fff, 'country': "Egypt", 'iso': "EG", 'flag': "🇪🇬", 'flag_image': "Egypt.png" },
  { 'start': 0x018000, 'end': 0x01ffff, 'country': "Libyan Arab Jamahiriya", 'iso': "LY", 'flag': "🇱🇾", 'flag_image': "Libya.png" },
  { 'start': 0x020000, 'end': 0x027fff, 'country': "Morocco", 'iso': "MA", 'iso': "MA", 'flag': "🇲🇦", 'flag_image': "Morocco.png" },
  { 'start': 0x028000, 'end': 0x02ffff, 'country': "Tunisia", 'iso': "", 'iso': "TN", 'flag': "🇹🇳", 'flag_image': "Tunisia.png" },
  { 'start': 0x030000, 'end': 0x0303ff, 'country': "Botswana", 'iso': "BW", 'flag': "🇧🇼", 'flag_image': "Botswana.png" },
  { 'start': 0x032000, 'end': 0x032fff, 'country': "Burundi", 'iso': "BI", 'flag': "🇧🇮", 'flag_image': "Burundi.png" },
  { 'start': 0x034000, 'end': 0x034fff, 'country': "Cameroon", 'iso': "CM", 'flag': "🇨🇲", 'flag_image': "Cameroon.png" },
  { 'start': 0x035000, 'end': 0x0353ff, 'country': "Comoros", 'iso': "KM", 'flag': "🇰🇲", 'flag_image': "Comoros.png" },
  { 'start': 0x036000, 'end': 0x036fff, 'country': "Congo", 'iso': "CG", 'flag': "🇨🇬", 'flag_image': "Republic_of_the_Congo.png" }, # probably?
  { 'start': 0x038000, 'end': 0x038fff, 'country': "Cote d'Ivoire", 'iso': "CI", 'flag': "🇨🇮", 'flag_image': "Cote_d_Ivoire.png" },
  { 'start': 0x03e000, 'end': 0x03efff, 'country': "Gabon", 'iso': "GA", 'flag': "🇬🇦", 'flag_image': "Gabon.png" },
  { 'start': 0x040000, 'end': 0x040fff, 'country': "Ethiopia", 'iso': "ET", 'flag': "🇪🇹", 'flag_image': "Ethiopia.png" },
  { 'start': 0x042000, 'end': 0x042fff, 'country': "Equatorial Guinea", 'iso': "GQ", 'flag': "🇬🇶", 'flag_image': "Equatorial_Guinea.png" },
  { 'start': 0x044000, 'end': 0x044fff, 'country': "Ghana", 'iso': "GH", 'flag': "🇬🇭", 'flag_image': "Ghana.png" },
  { 'start': 0x046000, 'end': 0x046fff, 'country': "Guinea", 'iso': "GN", 'flag': "🇬🇳", 'flag_image': "Guinea.png" },
  { 'start': 0x048000, 'end': 0x0483ff, 'country': "Guinea-Bissau", 'iso': "GW", 'flag': "🇬🇼", 'flag_image': "Guinea_Bissau.png" },
  { 'start': 0x04a000, 'end': 0x04a3ff, 'country': "Lesotho", 'iso': "LS", 'flag': "🇱🇸", 'flag_image': "Lesotho.png" },
  { 'start': 0x04c000, 'end': 0x04cfff, 'country': "Kenya", 'iso': "KE", 'flag': "🇰🇪", 'flag_image': "Kenya.png" },
  { 'start': 0x050000, 'end': 0x050fff, 'country': "Liberia", 'iso': "LR", 'flag': "🇱🇷", 'flag_image': "Liberia.png" },
  { 'start': 0x054000, 'end': 0x054fff, 'country': "Madagascar", 'iso': "MG", 'flag': "🇲🇬", 'flag_image': "Madagascar.png" },
  { 'start': 0x058000, 'end': 0x058fff, 'country': "Malawi", 'iso': "MW", 'flag': "🇲🇼", 'flag_image': "Malawi.png" },
  { 'start': 0x05a000, 'end': 0x05a3ff, 'country': "Maldives", 'iso': "MV", 'flag': "🇲🇻", 'flag_image': "Maldives.png" },
  { 'start': 0x05c000, 'end': 0x05cfff, 'country': "Mali", 'iso': "ML", 'flag': "🇲🇱", 'flag_image': "Mali.png" },
  { 'start': 0x05e000, 'end': 0x05e3ff, 'country': "Mauritania", 'iso': "MR", 'flag': "🇲🇷", 'flag_image': "Mauritania.png" },
  { 'start': 0x060000, 'end': 0x0603ff, 'country': "Mauritius", 'iso': "MU", 'flag': "🇲🇺", 'flag_image': "Mauritius.png" },
  { 'start': 0x062000, 'end': 0x062fff, 'country': "Niger", 'iso': "NE", 'flag': "🇳🇪", 'flag_image': "Niger.png" },
  { 'start': 0x064000, 'end': 0x064fff, 'country': "Nigeria", 'iso': "NG", 'flag': "🇳🇬", 'flag_image': "Nigeria.png" },
  { 'start': 0x068000, 'end': 0x068fff, 'country': "Uganda", 'iso': "UG", 'flag': "🇺🇬", 'flag_image': "Uganda.png" },
  { 'start': 0x06a000, 'end': 0x06a3ff, 'country': "Qatar", 'iso': "QA", 'flag': "🇶🇦", 'flag_image': "Qatar.png" },
  { 'start': 0x06c000, 'end': 0x06cfff, 'country': "Central African Republic", 'iso': "CF", 'flag': "🇨🇫", 'flag_image': "Central_African_Republic.png" },
  { 'start': 0x06e000, 'end': 0x06efff, 'country': "Rwanda", 'iso': "RW", 'flag': "🇷🇼", 'flag_image': "Rwanda.png" },
  { 'start': 0x070000, 'end': 0x070fff, 'country': "Senegal", 'iso': "SN", 'flag': "🇸🇳", 'flag_image': "Senegal.png" },
  { 'start': 0x074000, 'end': 0x0743ff, 'country': "Seychelles", 'iso': "SC", 'flag': "🇸🇨", 'flag_image': "Seychelles.png" },
  { 'start': 0x076000, 'end': 0x0763ff, 'country': "Sierra Leone", 'iso': "SL", 'flag': "🇸🇱", 'flag_image': "Sierra_Leone.png" },
  { 'start': 0x078000, 'end': 0x078fff, 'country': "Somalia", 'iso': "SO", 'flag': "🇸🇴", 'flag_image': "Somalia.png" },
  { 'start': 0x07a000, 'end': 0x07a3ff, 'country': "Swaziland", 'iso': "SZ", 'flag': "🇸🇿", 'flag_image': "Swaziland.png" },
  { 'start': 0x07c000, 'end': 0x07cfff, 'country': "Sudan", 'iso': "SD", 'flag': "🇸🇩", 'flag_image': "Sudan.png" },
  { 'start': 0x080000, 'end': 0x080fff, 'country': "Tanzania", 'iso': "TZ", 'flag': "🇹🇿", 'flag_image': "Tanzania.png" },
  { 'start': 0x084000, 'end': 0x084fff, 'country': "Chad", 'iso': "TD", 'flag': "🇹🇩", 'flag_image': "Chad.png" },
  { 'start': 0x088000, 'end': 0x088fff, 'country': "Togo", 'iso': "TG", 'flag': "🇹🇬", 'flag_image': "Togo.png" },
  { 'start': 0x08a000, 'end': 0x08afff, 'country': "Zambia", 'iso': "ZM", 'flag': "🇿🇲", 'flag_image': "Zambia.png" },
  { 'start': 0x08c000, 'end': 0x08cfff, 'country': "DR Congo", 'iso': "", 'flag': "🇨🇩", 'flag_image': "Democratic_Republic_of_the_Congo.png" },
  { 'start': 0x090000, 'end': 0x090fff, 'country': "Angola", 'iso': "AO", 'flag': "🇦🇴", 'flag_image': "Angola.png" },
  { 'start': 0x094000, 'end': 0x0943ff, 'country': "Benin", 'iso': "BJ", 'flag': "🇧🇯", 'flag_image': "Benin.png" },
  { 'start': 0x096000, 'end': 0x0963ff, 'country': "Cape Verde", 'iso': "CV", 'flag': "🇨🇻", 'flag_image': "Cape_Verde.png" },
  { 'start': 0x098000, 'end': 0x0983ff, 'country': "Djibouti", 'iso': "DJ", 'flag': "🇩🇯", 'flag_image': "Djibouti.png" },
  { 'start': 0x09a000, 'end': 0x09afff, 'country': "Gambia", 'iso': "GM", 'flag': "🇬🇲", 'flag_image': "Gambia.png" },
  { 'start': 0x09c000, 'end': 0x09cfff, 'country': "Burkina Faso", 'iso': "BF", 'flag': "🇧🇫", 'flag_image': "Burkina_Faso.png" },
  { 'start': 0x09e000, 'end': 0x09e3ff, 'country': "Sao Tome and Principe", 'iso': "ST", 'flag': "🇸🇹", 'flag_image': "Sao_Tome_and_Principe.png" },
  { 'start': 0x0a0000, 'end': 0x0a7fff, 'country': "Algeria", 'iso': "DZ", 'flag': "🇩🇿", 'flag_image': "Algeria.png" },
  { 'start': 0x0a8000, 'end': 0x0a8fff, 'country': "Bahamas", 'iso': "BS", 'flag': "🇧🇸", 'flag_image': "Bahamas.png" },
  { 'start': 0x0aa000, 'end': 0x0aa3ff, 'country': "Barbados", 'iso': "BB", 'flag': "🇧🇧", 'flag_image': "Barbados.png" },
  { 'start': 0x0ab000, 'end': 0x0ab3ff, 'country': "Belize", 'iso': "BZ", 'flag': "🇧🇿", 'flag_image': "Belize.png" },
  { 'start': 0x0ac000, 'end': 0x0acfff, 'country': "Colombia", 'iso': "SO", 'flag': "🇨🇴", 'flag_image': "Colombia.png" },
  { 'start': 0x0ae000, 'end': 0x0aefff, 'country': "Costa Rica", 'iso': "CR", 'flag': "🇨🇷", 'flag_image': "Costa_Rica.png" },
  { 'start': 0x0b0000, 'end': 0x0b0fff, 'country': "Cuba", 'iso': "CU", 'flag': "🇨🇺", 'flag_image': "Cuba.png" },
  { 'start': 0x0b2000, 'end': 0x0b2fff, 'country': "El Salvador", 'iso': "SV", 'flag': "🇸🇻", 'flag_image': "El_Salvador.png" },
  { 'start': 0x0b4000, 'end': 0x0b4fff, 'country': "Guatemala", 'iso': "GT", 'flag': "🇬🇹", 'flag_image': "Guatemala.png" },
  { 'start': 0x0b6000, 'end': 0x0b6fff, 'country': "Guyana", 'iso': "GY", 'flag': "🇬🇾", 'flag_image': "Guyana.png" },
  { 'start': 0x0b8000, 'end': 0x0b8fff, 'country': "Haiti", 'iso': "HT", 'flag': "🇭🇹", 'flag_image': "Haiti.png" },
  { 'start': 0x0ba000, 'end': 0x0bafff, 'country': "Honduras", 'iso': "HN", 'flag': "🇭🇳", 'flag_image': "Honduras.png" },
  { 'start': 0x0bc000, 'end': 0x0bc3ff, 'country': "Saint Vincent and the Grenadines", 'iso': "VC", 'flag': "🇻🇨", 'flag_image': "Saint_Vincent_and_the_Grenadines.png" },
  { 'start': 0x0be000, 'end': 0x0befff, 'country': "Jamaica", 'iso': "JM", 'flag': "🇯🇲", 'flag_image': "Jamaica.png" },
  { 'start': 0x0c0000, 'end': 0x0c0fff, 'country': "Nicaragua", 'iso': "NI", 'flag': "🇳🇮", 'flag_image': "Nicaragua.png" },
  { 'start': 0x0c2000, 'end': 0x0c2fff, 'country': "Panama", 'iso': "PA", 'flag': "🇵🇦", 'flag_image': "Panama.png" },
  { 'start': 0x0c4000, 'end': 0x0c4fff, 'country': "Dominican Republic", 'iso': "DO", 'flag': "🇩🇴", 'flag_image': "Dominican_Republic.png" },
  { 'start': 0x0c6000, 'end': 0x0c6fff, 'country': "Trinidad and Tobago", 'iso': "TT", 'flag': "🇹🇹", 'flag_image': "Trinidad_and_Tobago.png" },
  { 'start': 0x0c8000, 'end': 0x0c8fff, 'country': "Suriname", 'iso': "SR", 'flag': "🇸🇷", 'flag_image': "Suriname.png" },
  { 'start': 0x0ca000, 'end': 0x0ca3ff, 'country': "Antigua and Barbuda", 'iso': "AG", 'flag': "🇦🇬", 'flag_image': "Antigua_and_Barbuda.png" },
  { 'start': 0x0cc000, 'end': 0x0cc3ff, 'country': "Grenada", 'iso': "GD", 'flag': "🇬🇩", 'flag_image': "Grenada.png" },
  { 'start': 0x0d0000, 'end': 0x0d7fff, 'country': "Mexico", 'iso': "MX", 'flag': "🇲🇽", 'flag_image': "Mexico.png" },
  { 'start': 0x0d8000, 'end': 0x0dffff, 'country': "Venezuela", 'iso': "VE", 'flag': "🇻🇪", 'flag_image': "Venezuela.png" },
  { 'start': 0x100000, 'end': 0x1fffff, 'country': "Russia", 'iso': "RU", 'flag': "🇷🇺", 'flag_image': "Russian_Federation.png" },
  { 'start': 0x201000, 'end': 0x2013ff, 'country': "Namibia", 'iso': "NA", 'flag': "🇳🇦", 'flag_image': "Namibia.png" },
  { 'start': 0x202000, 'end': 0x2023ff, 'country': "Eritrea", 'iso': "ER", 'flag': "🇪🇷", 'flag_image': "Eritrea.png" },
  { 'start': 0x300000, 'end': 0x33ffff, 'country': "Italy", 'iso': "IT", 'flag': "🇮🇹", 'flag_image': "Italy.png" },
  { 'start': 0x340000, 'end': 0x37ffff, 'country': "Spain", 'iso': "ES", 'flag': "🇪🇸", 'flag_image': "Spain.png" },
  { 'start': 0x380000, 'end': 0x3bffff, 'country': "France", 'iso': "FR", 'flag': "🇫🇷", 'flag_image': "France.png" },
  { 'start': 0x3c0000, 'end': 0x3fffff, 'country': "Germany", 'iso': "DE", 'flag': "🇩🇪", 'flag_image': "Germany.png" },
#   UK territories are officially part of the UK range
#   add extra entries that are above the UK and take precedence
#   this is a mess ... let's still try
  { 'start': 0x400000, 'end': 0x4001bf, 'country': "Bermuda", 'iso': "BM", 'flag': "🇧🇲", 'flag_image': "Bermuda.png" },
  { 'start': 0x4001c0, 'end': 0x4001ff, 'country': "Cayman Islands", 'iso': "KY", 'flag': "🇰🇾", 'flag_image': "Cayman_Islands.png" },
  { 'start': 0x400300, 'end': 0x4003ff, 'country': "Turks and Caicos Islands", 'iso': "TC", 'flag': "🇹🇨", 'flag_image': "Turks_and_Caicos_Islands.png" },
  { 'start': 0x424135, 'end': 0x4241f2, 'country': "Cayman Islands", 'iso': "KY", 'flag': "🇰🇾", 'flag_image': "Cayman_Islands.png" },
  { 'start': 0x424200, 'end': 0x4246ff, 'country': "Bermuda", 'iso': "BM", 'flag': "🇧🇲", 'flag_image': "Bermuda.png" },
  { 'start': 0x424700, 'end': 0x424899, 'country': "Cayman Islands", 'iso': "KY", 'flag': "🇰🇾", 'flag_image': "Cayman_Islands.png" },
  { 'start': 0x424b00, 'end': 0x424bff, 'country': "Isle of Man", 'iso': "IM", 'flag': "🇮🇲", 'flag_image': "Isle_of_Man.png" },
  { 'start': 0x43be00, 'end': 0x43beff, 'country': "Bermuda", 'iso': "BM", 'flag': "🇧🇲", 'flag_image': "Bermuda.png" },
  { 'start': 0x43e700, 'end': 0x43eafd, 'country': "Isle of Man", 'iso': "IM", 'flag': "🇮🇲", 'flag_image': "Isle_of_Man.png" },
  { 'start': 0x43eafe, 'end': 0x43eeff, 'country': "Guernsey", 'iso': "GG", 'flag': "🇬🇬", 'flag_image': "Guernsey.png" },
  # catch all United Kingdom for the even more obscure stuff
  { 'start': 0x400000, 'end': 0x43ffff, 'country': "United Kingdom", 'iso': "GB", 'flag': "🇬🇧", 'flag_image': "United_Kingdom.png" },
  { 'start': 0x440000, 'end': 0x447fff, 'country': "Austria", 'iso': "AT", 'flag': "🇦🇹", 'flag_image': "Austria.png" },
  { 'start': 0x448000, 'end': 0x44ffff, 'country': "Belgium", 'iso': "BE", 'flag': "🇧🇪", 'flag_image': "Belgium.png" },
  { 'start': 0x450000, 'end': 0x457fff, 'country': "Bulgaria", 'iso': "BG", 'flag': "🇧🇬", 'flag_image': "Bulgaria.png" },
  { 'start': 0x458000, 'end': 0x45ffff, 'country': "Denmark", 'iso': "DK", 'flag': "🇩🇰", 'flag_image': "Denmark.png" },
  { 'start': 0x460000, 'end': 0x467fff, 'country': "Finland", 'iso': "FI", 'flag': "🇫🇮", 'flag_image': "Finland.png" },
  { 'start': 0x468000, 'end': 0x46ffff, 'country': "Greece", 'iso': "GR", 'flag': "🇬🇷", 'flag_image': "Greece.png" },
  { 'start': 0x470000, 'end': 0x477fff, 'country': "Hungary", 'iso': "HU", 'flag': "🇭🇺", 'flag_image': "Hungary.png" },
  { 'start': 0x478000, 'end': 0x47ffff, 'country': "Norway", 'iso': "NO", 'flag': "🇳🇴", 'flag_image': "Norway.png" },
  { 'start': 0x480000, 'end': 0x487fff, 'country': "Kingdom of the Netherlands", 'iso': "NL", 'flag': "🇳🇱", 'flag_image': "Netherlands.png" },
  { 'start': 0x488000, 'end': 0x48ffff, 'country': "Poland", 'iso': "PL", 'flag': "🇵🇱", 'flag_image': "Poland.png" },
  { 'start': 0x490000, 'end': 0x497fff, 'country': "Portugal", 'iso': "PT", 'flag': "🇵🇹", 'flag_image': "Portugal.png" },
  { 'start': 0x498000, 'end': 0x49ffff, 'country': "Czechia", 'iso': "CZ", 'flag': "🇨🇿", 'flag_image': "Czech_Republic.png" },
  { 'start': 0x4a0000, 'end': 0x4a7fff, 'country': "Romania", 'iso': "RO", 'flag': "🇷🇴", 'flag_image': "Romania.png" },
  { 'start': 0x4a8000, 'end': 0x4affff, 'country': "Sweden", 'iso': "SE", 'flag': "🇸🇪", 'flag_image': "Sweden.png" },
  { 'start': 0x4b0000, 'end': 0x4b7fff, 'country': "Switzerland", 'iso': "CH", 'flag': "🇨🇭", 'flag_image': "Switzerland.png" },
  { 'start': 0x4b8000, 'end': 0x4bffff, 'country': "Turkey", 'iso': "TR", 'flag': "🇹🇷", 'flag_image': "Turkey.png" },
  { 'start': 0x4c0000, 'end': 0x4c7fff, 'country': "Serbia", 'iso': "RS", 'flag': "🇷🇸", 'flag_image': "Serbia.png" },
  { 'start': 0x4c8000, 'end': 0x4c83ff, 'country': "Cyprus", 'iso': "CY", 'flag': "🇨🇾", 'flag_image': "Cyprus.png" },
  { 'start': 0x4ca000, 'end': 0x4cafff, 'country': "Ireland", 'iso': "IE", 'flag': "🇮🇪", 'flag_image': "Ireland.png" },
  { 'start': 0x4cc000, 'end': 0x4ccfff, 'country': "Iceland", 'iso': "IS", 'flag': "🇮🇸", 'flag_image': "Iceland.png" },
  { 'start': 0x4d0000, 'end': 0x4d03ff, 'country': "Luxembourg", 'iso': "LU", 'flag': "🇱🇺", 'flag_image': "Luxembourg.png" },
  { 'start': 0x4d2000, 'end': 0x4d2fff, 'country': "Malta", 'iso': "MT", 'flag': "🇲🇹", 'flag_image': "Malta.png" },
  { 'start': 0x4d4000, 'end': 0x4d43ff, 'country': "Monaco", 'iso': "MC", 'flag': "🇲🇨", 'flag_image': "Monaco.png" },
  { 'start': 0x500000, 'end': 0x5003ff, 'country': "San Marino", 'iso': "SM", 'flag': "🇸🇲", 'flag_image': "San_Marino.png" },
  { 'start': 0x501000, 'end': 0x5013ff, 'country': "Albania", 'iso': "AL", 'flag': "🇦🇱", 'flag_image': "Albania.png" },
  { 'start': 0x501c00, 'end': 0x501fff, 'country': "Croatia", 'iso': "HR", 'flag': "🇭🇷", 'flag_image': "Croatia.png" },
  { 'start': 0x502c00, 'end': 0x502fff, 'country': "Latvia", 'iso': "LV", 'flag': "🇱🇻", 'flag_image': "Latvia.png" },
  { 'start': 0x503c00, 'end': 0x503fff, 'country': "Lithuania", 'iso': "LT", 'flag': "🇱🇹", 'flag_image': "Lithuania.png" },
  { 'start': 0x504c00, 'end': 0x504fff, 'country': "Moldova", 'iso': "MD", 'flag': "🇲🇩", 'flag_image': "Moldova.png" },
  { 'start': 0x505c00, 'end': 0x505fff, 'country': "Slovakia", 'iso': "SK", 'flag': "🇸🇰", 'flag_image': "Slovakia.png" },
  { 'start': 0x506c00, 'end': 0x506fff, 'country': "Slovenia", 'iso': "SI", 'flag': "🇸🇮", 'flag_image': "Slovenia.png" },
  { 'start': 0x507c00, 'end': 0x507fff, 'country': "Uzbekistan", 'iso': "UZ", 'flag': "🇺🇿", 'flag_image': "Uzbekistan.png" },
  { 'start': 0x508000, 'end': 0x50ffff, 'country': "Ukraine", 'iso': "UA", 'flag': "🇺🇦", 'flag_image': "Ukraine.png" },
  { 'start': 0x510000, 'end': 0x5103ff, 'country': "Belarus", 'iso': "BY", 'flag': "🇧🇾", 'flag_image': "Belarus.png" },
  { 'start': 0x511000, 'end': 0x5113ff, 'country': "Estonia", 'iso': "EE", 'flag': "🇪🇪", 'flag_image': "Estonia.png" },
  { 'start': 0x512000, 'end': 0x5123ff, 'country': "Macedonia", 'iso': "MK", 'flag': "🇲🇰", 'flag_image': "Macedonia.png" },
  { 'start': 0x513000, 'end': 0x5133ff, 'country': "Bosnia and Herzegovina", 'iso': "BA", 'flag': "🇧🇦", 'flag_image': "Bosnia.png" },
  { 'start': 0x514000, 'end': 0x5143ff, 'country': "Georgia", 'iso': "GE", 'flag': "🇬🇪", 'flag_image': "Georgia.png" },
  { 'start': 0x515000, 'end': 0x5153ff, 'country': "Tajikistan", 'iso': "TJ", 'flag': "🇹🇯", 'flag_image': "Tajikistan.png" },
  { 'start': 0x516000, 'end': 0x5163ff, 'country': "Montenegro", 'iso': "ME", 'flag': "🇲🇪", 'flag_image': "Montenegro.png" },
  { 'start': 0x600000, 'end': 0x6003ff, 'country': "Armenia", 'iso': "AM", 'flag': "🇦🇲", 'flag_image': "Armenia.png" },
  { 'start': 0x600800, 'end': 0x600bff, 'country': "Azerbaijan", 'iso': "AZ", 'flag': "🇦🇿", 'flag_image': "Azerbaijan.png" },
  { 'start': 0x601000, 'end': 0x6013ff, 'country': "Kyrgyzstan", 'iso': "KG", 'flag': "🇰🇬", 'flag_image': "Kyrgyzstan.png" },
  { 'start': 0x601800, 'end': 0x601bff, 'country': "Turkmenistan", 'iso': "TM", 'flag': "🇹🇲", 'flag_image': "Turkmenistan.png" },
  { 'start': 0x680000, 'end': 0x6803ff, 'country': "Bhutan", 'iso': "BT", 'flag': "🇧🇹", 'flag_image': "Bhutan.png" },
  { 'start': 0x681000, 'end': 0x6813ff, 'country': "Micronesia, Federated States of", 'iso': "FM", 'flag': "🇫🇲", 'flag_image': "Micronesia.png" },
  { 'start': 0x682000, 'end': 0x6823ff, 'country': "Mongolia", 'iso': "MN", 'flag': "🇲🇳", 'flag_image': "Mongolia.png" },
  { 'start': 0x683000, 'end': 0x6833ff, 'country': "Kazakhstan", 'iso': "KZ", 'flag': "🇰🇿", 'flag_image': "Kazakhstan.png" },
  { 'start': 0x684000, 'end': 0x6843ff, 'country': "Palau", 'iso': "PW", 'flag': "🇵🇼", 'flag_image': "Palau.png" },
  { 'start': 0x700000, 'end': 0x700fff, 'country': "Afghanistan", 'iso': "AF", 'flag': "🇦🇫", 'flag_image': "Afghanistan.png" },
  { 'start': 0x702000, 'end': 0x702fff, 'country': "Bangladesh", 'iso': "BD", 'flag': "🇧🇩", 'flag_image': "Bangladesh.png" },
  { 'start': 0x704000, 'end': 0x704fff, 'country': "Myanmar", 'iso': "MM", 'flag': "🇲🇲", 'flag_image': "Myanmar.png" },
  { 'start': 0x706000, 'end': 0x706fff, 'country': "Kuwait", 'iso': "KW", 'flag': "🇰🇼", 'flag_image': "Kuwait.png" },
  { 'start': 0x708000, 'end': 0x708fff, 'country': "Laos", 'iso': "LA", 'flag': "🇱🇦", 'flag_image': "Laos.png" },
  { 'start': 0x70a000, 'end': 0x70afff, 'country': "Nepal", 'iso': "NP", 'flag': "🇳🇵", 'flag_image': "Nepal.png" },
  { 'start': 0x70c000, 'end': 0x70c3ff, 'country': "Oman", 'iso': "OM", 'flag': "🇴🇲", 'flag_image': "Oman.png" },
  { 'start': 0x70e000, 'end': 0x70efff, 'country': "Cambodia", 'iso': "KH", 'flag': "🇰🇭", 'flag_image': "Cambodia.png" },
  { 'start': 0x710000, 'end': 0x717fff, 'country': "Saudi Arabia", 'iso': "SA", 'flag': "🇸🇦", 'flag_image': "Saudi_Arabia.png" },
  { 'start': 0x718000, 'end': 0x71ffff, 'country': "South Korea", 'iso': "KR", 'flag': "🇰🇷", 'flag_image': "South_Korea.png" },
  { 'start': 0x720000, 'end': 0x727fff, 'country': "North Korea", 'iso': "KP", 'flag': "🇰🇵", 'flag_image': "North_Korea.png" },
  { 'start': 0x728000, 'end': 0x72ffff, 'country': "Iraq", 'iso': "IQ", 'flag': "🇮🇶", 'flag_image': "Iraq.png" },
  { 'start': 0x730000, 'end': 0x737fff, 'country': "Iran", 'iso': "IR", 'flag': "🇮🇷", 'flag_image': "Iran.png" },
  { 'start': 0x738000, 'end': 0x73ffff, 'country': "Israel", 'iso': "IL", 'flag': "🇮🇱", 'flag_image': "Israel.png" },
  { 'start': 0x740000, 'end': 0x747fff, 'country': "Jordan", 'iso': "JO", 'flag': "🇯🇴", 'flag_image': "Jordan.png" },
  { 'start': 0x748000, 'end': 0x74ffff, 'country': "Lebanon", 'iso': "LB", 'flag': "🇱🇧", 'flag_image': "Lebanon.png" },
  { 'start': 0x750000, 'end': 0x757fff, 'country': "Malaysia", 'iso': "MY", 'flag': "🇲🇾", 'flag_image': "Malaysia.png" },
  { 'start': 0x758000, 'end': 0x75ffff, 'country': "Philippines", 'iso': "PH", 'flag': "🇵🇭", 'flag_image': "Philippines.png" },
  { 'start': 0x760000, 'end': 0x767fff, 'country': "Pakistan", 'iso': "PK", 'flag': "🇵🇰", 'flag_image': "Pakistan.png" },
  { 'start': 0x768000, 'end': 0x76ffff, 'country': "Singapore", 'iso': "SG", 'flag': "🇸🇬", 'flag_image': "Singapore.png" },
  { 'start': 0x770000, 'end': 0x777fff, 'country': "Sri Lanka", 'iso': "LK", 'flag': "🇱🇰", 'flag_image': "Sri_Lanka.png" },
  { 'start': 0x778000, 'end': 0x77ffff, 'country': "Syria", 'iso': "SY", 'flag': "🇸🇾", 'flag_image': "Syria.png" },
  { 'start': 0x789000, 'end': 0x789fff, 'country': "Hong Kong", 'iso': "HK", 'flag': "🇭🇰", 'flag_image': "Hong_Kong.png" },
  { 'start': 0x780000, 'end': 0x7bffff, 'country': "China", 'iso': "CN", 'flag': "🇨🇳", 'flag_image': "China.png" },
  { 'start': 0x7c0000, 'end': 0x7fffff, 'country': "Australia", 'iso': "AU", 'flag': "🇦🇺", 'flag_image': "Australia.png" },
  { 'start': 0x800000, 'end': 0x83ffff, 'country': "India", 'iso': "IN", 'flag': "🇮🇳", 'flag_image': "India.png" },
  { 'start': 0x840000, 'end': 0x87ffff, 'country': "Japan", 'iso': "JP", 'flag': "🇯🇵", 'flag_image': "Japan.png" },
  { 'start': 0x880000, 'end': 0x887fff, 'country': "Thailand", 'iso': "TH", 'flag': "🇹🇭", 'flag_image': "Thailand.png" },
  { 'start': 0x888000, 'end': 0x88ffff, 'country': "Viet Nam", 'iso': "VN", 'flag': "🇻🇳", 'flag_image': "Vietnam.png" },
  { 'start': 0x890000, 'end': 0x890fff, 'country': "Yemen", 'iso': "YE", 'flag': "🇾🇪", 'flag_image': "Yemen.png" },
  { 'start': 0x894000, 'end': 0x894fff, 'country': "Bahrain", 'iso': "BH", 'flag': "🇧🇭", 'flag_image': "Bahrain.png" },
  { 'start': 0x895000, 'end': 0x8953ff, 'country': "Brunei", 'iso': "BN", 'flag': "🇧🇳", 'flag_image': "Brunei.png" },
  { 'start': 0x896000, 'end': 0x896fff, 'country': "United Arab Emirates", 'iso': "AE", 'flag': "🇦🇪", 'flag_image': "UAE.png" },
  { 'start': 0x897000, 'end': 0x8973ff, 'country': "Solomon Islands", 'iso': "SB", 'flag': "🇸🇧", 'flag_image': "Soloman_Islands.png" }, # flag typo?
  { 'start': 0x898000, 'end': 0x898fff, 'country': "Papua New Guinea", 'iso': "PG", 'flag': "🇵🇬", 'flag_image': "Papua_New_Guinea.png" },
  { 'start': 0x899000, 'end': 0x8993ff, 'country': "Taiwan", 'iso': "TW", 'flag': "🇹🇼", 'flag_image': "Taiwan.png" },
  { 'start': 0x8a0000, 'end': 0x8a7fff, 'country': "Indonesia", 'iso': "ID", 'flag': "🇮🇩", 'flag_image': "Indonesia.png" },
  { 'start': 0x900000, 'end': 0x9003ff, 'country': "Marshall Islands", 'iso': "MH", 'flag': "🇲🇭", 'flag_image': "Marshall_Islands.png" },
  { 'start': 0x901000, 'end': 0x9013ff, 'country': "Cook Islands", 'iso': "CK", 'flag': "🇨🇰", 'flag_image': "Cook_Islands.png" },
  { 'start': 0x902000, 'end': 0x9023ff, 'country': "Samoa", 'iso': "WS", 'flag': "🇼🇸", 'flag_image': "Samoa.png" },
  { 'start': 0xa00000, 'end': 0xafffff, 'country': "United States", 'iso': "US", 'flag': "🇺🇸", 'flag_image': "United_States_of_America.png" },
  { 'start': 0xc00000, 'end': 0xc3ffff, 'country': "Canada", 'iso': "CA", 'flag': "🇨🇦", 'flag_image': "Canada.png" },
  { 'start': 0xc80000, 'end': 0xc87fff, 'country': "New Zealand", 'iso': "NZ", 'flag': "🇳🇿", 'flag_image': "New_Zealand.png" },
  { 'start': 0xc88000, 'end': 0xc88fff, 'country': "Fiji", 'iso': "FJ", 'flag': "🇫🇯", 'flag_image': "Fiji.png" },
  { 'start': 0xc8a000, 'end': 0xc8a3ff, 'country': "Nauru", 'iso': "NR", 'flag': "🇳🇷", 'flag_image': "Nauru.png" },
  { 'start': 0xc8c000, 'end': 0xc8c3ff, 'country': "Saint Lucia", 'iso': "LC", 'flag': "🇱🇨", 'flag_image': "Saint_Lucia.png" },
  { 'start': 0xc8d000, 'end': 0xc8d3ff, 'country': "Tonga", 'iso': "TO", 'flag': "🇹🇴", 'flag_image': "Tonga.png" },
  { 'start': 0xc8e000, 'end': 0xc8e3ff, 'country': "Kiribati", 'iso': "KI", 'flag': "🇰🇮", 'flag_image': "Kiribati.png" },
  { 'start': 0xc90000, 'end': 0xc903ff, 'country': "Vanuatu", 'iso': "VU", 'flag': "🇻🇺", 'flag_image': "Vanuatu.png" },
  { 'start': 0xe00000, 'end': 0xe3ffff, 'country': "Argentina", 'iso': "AR", 'flag': "🇦🇷", 'flag_image': "Argentina.png" },
  { 'start': 0xe40000, 'end': 0xe7ffff, 'country': "Brazil", 'iso': "BR", 'flag': "🇧🇷", 'flag_image': "Brazil.png" },
  { 'start': 0xe80000, 'end': 0xe80fff, 'country': "Chile", 'iso': "CL", 'flag': "🇨🇱", 'flag_image': "Chile.png" },
  { 'start': 0xe84000, 'end': 0xe84fff, 'country': "Ecuador", 'iso': "EC", 'flag': "🇪🇨", 'flag_image': "Ecuador.png" },
  { 'start': 0xe88000, 'end': 0xe88fff, 'country': "Paraguay", 'iso': "PY", 'flag': "🇵🇾", 'flag_image': "Paraguay.png" },
  { 'start': 0xe8c000, 'end': 0xe8cfff, 'country': "Peru", 'iso': "PE", 'flag': "🇵🇪", 'flag_image': "Peru.png" },
  { 'start': 0xe90000, 'end': 0xe90fff, 'country': "Uruguay", 'iso': "UY", 'flag': "🇺🇾", 'flag_image': "Uruguay.png" },
  { 'start': 0xe94000, 'end': 0xe94fff, 'country': "Bolivia", 'iso': "BO", 'flag': "🇧🇴", 'flag_image': "Bolivia.png" },
  { 'start': 0xf00000, 'end': 0xf07fff, 'country': "ICAO (temporary)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0xf09000, 'end': 0xf093ff, 'country': "ICAO (special use)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },

  # Block assignments mentioned in Chapter 9 section 4, at the end so they are only used if
  # nothing above applies
  { 'start': 0x200000, 'end': 0x27ffff, 'country': "Unassigned (AFI region)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0x280000, 'end': 0x28ffff, 'country': "Unassigned (SAM region)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0x500000, 'end': 0x5fffff, 'country': "Unassigned (EUR / NAT regions)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0x600000, 'end': 0x67ffff, 'country': "Unassigned (MID region)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0x680000, 'end': 0x6fffff, 'country': "Unassigned (ASIA region)", 'iso': "", 'flag': "",'flag_image': "blank.png" },
  { 'start': 0x900000, 'end': 0x9fffff, 'country': "Unassigned (NAM / PAC regions)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0xb00000, 'end': 0xbfffff, 'country': "Unassigned (reserved for future use)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0xec0000, 'end': 0xefffff, 'country': "Unassigned (CAR region)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0xd00000, 'end': 0xdfffff, 'country': "Unassigned (reserved for future use)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
  { 'start': 0xf00000, 'end': 0xffffff, 'country': "Unassigned (reserved for future use)", 'iso': "", 'flag': "", 'flag_image': "blank.png" },
];

# let unassigned_range = {
#   'country': "Unassigned",
#   'flag_image': null,
# };
unassigned_range = {
    "country": "Unassigned",
    "flag_image": None,
    "iso":'zz'
}


# Given a (hex string) ICAO address,
# return an object describing that ICAO range.
# Always returns a non-null object.
##   (todo: binary search)

def find_icao_range(icao):
    

    if icao == '------' :
        return ''
    
    hexa = int(icao, 16)
    
    
    iso = ''
    for icao_range in ICAO_Ranges:
        if hexa >= icao_range['start'] and hexa <= icao_range['end']:
            iso = icao_range['iso']
            # print(icao,hexa,iso)
            return iso

    return ''


# print(find_icao_range("4BC85A"));