[tool.poetry]
name = "fr24"
homepage = "https://github.com/xoolive/fr24/"
version = "0.1.0"
description = "Parse gRPC data from FlightRadar24"
authors = ["Xavier Olive <git@xoolive.org>"]
license = "MIT"
include = [
    "request.proto"
]

[tool.poetry.scripts]
fr24 = 'fr24.livefeed:snapshot'
aircraft_db = 'fr24.mongo:aircraft_db'

[tool.poetry.extras]
mongo = ['pymongo', 'motor', 'sshtunnel']

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pandas = "^2.1.3"
pyarrow = "^14.0.1"
httpx = "^0.25.1"
protobuf = "^4.25.0"
brotli = "^1.1.0"
pymongo = { version = "^4.6.0", optional = true }
motor = { version = "^3.3.2", optional = true }
sshtunnel = { version = "^0.4.0", optional = true }

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
ruff = "^0.1.5"
mypy = "^1.7.0"
types-protobuf = "^4.24.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]

[tool.ruff]
select = [
  "E", "W",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
  "NPY",  # numpy
  # "PD",  # pandas
  "DTZ", # flake8-datetimez
  "RUF"
]
exclude = ["proto"]
line-length = 80
target-version = "py39"

[tool.ruff.isort]
known-first-party = ["numpy", "pandas"]

[tool.mypy]
python_version = 3.9
exclude = "proto"
platform = "posix"

color_output = true
pretty = true
show_column_numbers = true
strict = true
check_untyped_defs = true
ignore_missing_imports = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
